### ISSUE TITLE
Concept for Responsible View

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#122]
Make a visual concept on how a view with responsible tree lists etc. could look like.

**Comment by MBuchalik** [comment]
![grafik](https://user-images.githubusercontent.com/8061217/213450175-ff2b12e4-994e-43e5-9cca-58d487f24285.png)
![grafik](https://user-images.githubusercontent.com/8061217/213450214-ff10b940-e168-43f6-99ba-df23db8cd16f.png)
![grafik](https://user-images.githubusercontent.com/8061217/213450265-36c2f094-58ed-4cd4-9b82-86129b7f7074.png)
![grafik](https://user-images.githubusercontent.com/8061217/213450318-8f0d786b-cfd7-4a0e-abbb-d8b4deb46331.png)
