### ISSUE TITLE
Enhanced CLI with Node Project

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#155]
Use the access token mechanism for API. Make sure we don't expose secrets.

**Comment by MBuchalik** [comment]
*The following is just a bunch of notes I took when learning about CLI design. I wanted to preserve this list somewhere, so here we go 😄*

A talk about the design of the GitHub CLI: https://www.youtube.com/watch?v=zsjeZZVAk1E
--> Related: https://primer.style/cli/getting-started/prototyping

The code of the GitHub CLI (https://github.com/cli/cli) is structured in the same way as the available commands:

```
pkg/
`-- cmd/
    |-- actions/
    |-- alias/
    |-- api/
    |-- auth/
    |   |-- gitcredential/ [this is no actual command]
    |   |-- login/
    |   |-- logout/
    |   |-- refresh/
    |   |-- setupgit/ [maps to the "setup-git" command]
    |   |-- shared/ [this is no actual command]
    |   |-- status/
    |   |-- token/
    |   `-- auth.go
    |-- browse/
    `-- codespace/
```



# Screenshots from the GitHub CLI

<details>

![grafik](https://user-images.githubusercontent.com/8061217/220074945-b7bdbf69-a86e-4061-8edc-831e707c6e84.png)
![grafik](https://user-images.githubusercontent.com/8061217/220074993-0a346c7b-4d90-47b9-9b82-ce8d78cc97fa.png)
![grafik](https://user-images.githubusercontent.com/8061217/220075069-6f4c7052-fdaf-4665-bc9b-62f9dca152bd.png)
![grafik](https://user-images.githubusercontent.com/8061217/220075162-fdcfa213-c738-4f1e-a710-c8987b765475.png)
![grafik](https://user-images.githubusercontent.com/8061217/220075235-e3c8d3b5-65b9-47c1-8d13-1797941078d2.png)
![grafik](https://user-images.githubusercontent.com/8061217/220075414-fdde5556-c161-49c6-8d1b-55a0a832522a.png)

</details>

**Comment by MBuchalik** [comment]
# Commands

## `msadoc`

<details>

```
> msadoc

USAGE
  msadoc <command> <subcommand> [flags]

CORE COMMANDS
  check: Check whether a given Service Doc is valid
  upload: Send a Service Doc to a server
  server: Manage login credentials for servers
```

</details>

## `msadoc server`

<details>

```
> msadoc server

Manage login credentials for MSAdoc servers.

USAGE
  msadoc server <command> [flags]

COMMANDS
  add: Add a new server (this is essentially a login command)
  delete: Remove a server
  list: List all servers
```

</details>

## `msadoc server add`

<details>

This is an interactive prompt, asking for:
- The server URL
- Username
- Password

```
> msadoc server add

? The URL to the server: https://example.com
```
```
> msadoc server add

? The URL to the server: https://example.com
? Username: john-doe
? Password: *********
```
```
> msadoc server add

? The URL to the server: https://example.com
? Username: john-doe
? Password: *********

Successfully added server "https://example.com".
```

In case of an error, we simply abort. This is probably not ideal for UX, but should be good enough for now.

```
> msadoc server add

? The URL to the server: https://example.com
? Username: john-doe
? Password: *********

Failed to authenticate on "https://example.com".
```

</details>

## `msadoc check`

<details>

```
> msadoc check

Check whether a Service Doc is valid.

USAGE
  msadoc check <path-to-file>

EXAMPLE
  msadoc check ./service-doc.json
```

```
> msadoc check ./valid-service-doc.json
The Service Doc is valid.
```

```
> msadoc check ./invalid-service-doc.json
The Service Doc is invalid. Errors:
- Mandatory field "name" is missing.
- Field "tags" must be an array, string given.
```

</details>

## `msadoc upload`

<details>

```
> msadoc upload

Upload a Service Doc to a server.

In an interactive shell, this command will ask you to select a server you want to perform the upload to. In a non-interactive shell like a CI environment, please specify the following two environment variables:
- MSADOC_SERVER: The URL to the server, e.g. https://example.com
- MSADOC_AUTH_TOKEN: The auth token that shall be used to authenticate to MSADOC_SERVER

USAGE
  msadoc upload <path-to-file>

EXAMPLE
  msadoc upload ./service-doc.json
```

Interactive shell:
```
> msadoc upload ./service-doc.json

? Which server would you like to upload the Service Doc to?
  > https://example1.com
    https://example2.org
```

CI environment:

```
> msadoc upload ./service-doc.json
The Service Doc has successfully been uploaded to "https://example.com".
```

Missing environment variables:
```
> msadoc upload ./service-doc.json
You are running this command in a non-interactive shell. For this to work, please specify the following environment variables:
- MSADOC_SERVER: The URL to the server, e.g. https://example.com
- MSADOC_AUTH_TOKEN: The auth token that shall be used to authenticate to MSADOC_SERVER
```

</details>

**Comment by MBuchalik** [comment]
Update: Version number will, for now, be taken from `cli/package.json`.

**Comment by georg-schwarz** [comment]
Deployment in #164
