### ISSUE TITLE
Refactor Dependencies Headings

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#67]
I think the first lines of code below should belong to the component one level above:

```
 <Typography variant="h3">Dependencies</Typography>
      <Box sx={{ marginTop: 2 }}>
        <Button
          variant="outlined"
          onClick={(): void => controller.setShowVisualization(true)}
        >
          Open Visualization
        </Button>
      </Box>
....
```

I think it makes sense to show different headings depending on the user sees the dependencies of a service or a group because presenting the same thing might cause confusion. Thus, I'd call it `Service Dependencies` for services, and `Aggregated Dependencies` for groups to highlight where we currently are.

_Originally posted by @georg-schwarz in https://github.com/osrgroup/msadoc/pull/66#discussion_r1011374567_

**Comment by MBuchalik** [comment]
As discusssed: Just refactor the component to use different heading based on input.
