### ISSUE TITLE
Frontend: Refresh Access Token Edge Cases

### ISSUE THREAD

**Issue by georg-schwarz** [osrgroup/msadoc#92]
> For example, imagine a user who has opened the page and left it open in the background for a few hours. I could imagine that some browsers may decide to throttle/stop the periodic token refreshing, which in turn leads to the application becoming unusable until the user manually refreshes the page.

I'm not sure how browsers act in that regard. Would they un-throttle/start the refreshing again when you focus the tab?
Maybe we can solve this by having a common error screen that allows refreshing the page (instead of redoing the API call)?

_Originally posted by @georg-schwarz in https://github.com/osrgroup/msadoc/issues/91#issuecomment-1324685588_

**Comment by MBuchalik** [comment]
I must say that I also don't know how browsers act in that case. My assumption was based on two ideas:
1. People like to keep lots of tabs open. If all tabs were run as if they were in the foreground, the CPU would basically melt. So there must be some kind of throttling.
2. In Chromium-based hybrid apps built with Cordova, I had issues with native features where, after a few hours of having the app in the background, certain APIs would simply stop working.

I have found out that Chrome does indeed throttle background tabs: https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html and https://docs.google.com/document/d/11FhKHRcABGS4SWPFGwoL6g0ALMqrFKapCk5ZTKKupEk/view

Other browsers might implement this in a different way.

My suggestion: Let's just observe whether this affects us. If we don't see any issues, then I would simply leave it as-is. But if we observe issues with this (or we get reports from users that might be related to this), then we already know where the problems are located. 😃 To add a potential fix, I have three suggestions:
1. There is a function called `window.onfocus` which allows us to run a function whenever our tab is focused. So: Store when the last refreshing took place, and in `window.onfocus` run the refreshing logic if it was more than 2 minutes ago.
2. Add the refreshing-on-401 logic back to our HTTP service
3. Technically, we could indeed also show an error screen that allows to refresh the page. But I guess the first ideas would be a bit more user-friendly?

**Comment by MBuchalik** [comment]
Should we maybe close this issue since we probably won't change the current refreshing mechanisms in the near future?
